---
- name: Configuration Management Example
  hosts: all
  connection: local
  become: yes

  tasks:
    - name: Ensure user "manju" exists
      user:
        name: manju
        state: present
        shell: /bin/bash
        create_home: yes

    - name: Ensure directory /opt/project exists
      file:
        path: /opt/project
        state: directory
        mode: '0755'

    - name: Ensure /opt/project/config.txt file exists with content
      copy:
        dest: /opt/project/config.txt
        content: |
          # Project Configurations
          app_mode = "development"
          version = 1.0
        mode: '0644'

    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start nginx directly (since systemctl won't work in WSL1)
      command: nginx
      ignore_errors: yes
